name: karmav1
on:
 #pull_request:
  push:
    branches:
    - main    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      id: cache
      with:
        path: "./ArtemPbookPractice/package.json"
        key: ${{ runner.os }}-npm-${{ hashFiles('/ArtemPbookPractice/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: npm install, build, and test
      run: |
       npm cache clean --force
        npm install
       
        npm update
        npm cache clean --force
        npm install
        npm run build
        npm test
        env:
        CI: true
