# This is a basic workflow to help you get started with Actions

#name: karmav4

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  #push:
   # branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install, build, and test
        run: |
         npm install
         npm run bootstrap
         npm run build
         npm test
         env:
          CI: true
        
          
